<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Persistence\Fire3DDbContext.Enums.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Persistence\Fire3DDbContext.Enums.cs" />
  </ItemGroup>


	<ItemGroup>
		<PackageReference Include="AWSSDK.Core" Version="*" />
		<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="*" />
		<PackageReference Include="AWSSDK.S3" Version="*" />
		<PackageReference Include="EFCore.NamingConventions" Version="10.*" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.*" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MiniExcel" Version="*" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="*" />
		<PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.12" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.*" />
		
	</ItemGroup>


	<ItemGroup>
	  <ProjectReference Include="..\Fire3D.Application\Fire3D.Application.csproj" />
	  <ProjectReference Include="..\Fire3D.Domain\Fire3D.Domain.csproj" />
	</ItemGroup>
	
	
</Project>
