\set ON_ERROR_STOP on
BEGIN;
\ir fixtures.sql
CREATE TEMP TABLE test_results(name TEXT PRIMARY KEY, outcome TEXT NOT NULL);
CREATE FUNCTION pg_temp.check_ok(label TEXT, condition BOOLEAN) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN IF condition IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAIL: %',label; END IF;
INSERT INTO test_results VALUES(label,'PASS'); END $$;
CREATE FUNCTION pg_temp.check_fail(label TEXT, command TEXT, expected TEXT) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
 BEGIN EXECUTE command;
 EXCEPTION WHEN OTHERS THEN
   IF SQLERRM NOT ILIKE '%'||expected||'%' THEN RAISE EXCEPTION 'FAIL %: unexpected error %',label,SQLERRM; END IF;
   INSERT INTO test_results VALUES(label,'PASS'); RETURN;
 END;
 RAISE EXCEPTION 'FAIL %: statement unexpectedly succeeded',label;
END $$;
SELECT pg_temp.check_ok('Multiple scenario versions confirmed on same revision',(SELECT count(*)=2 FROM revision_reviews WHERE action='ConfirmForTraining'));
SELECT pg_temp.check_ok('Shared installation supports two user registrations',(SELECT count(*)=2 FROM user_devices WHERE device_uuid='shared-install'));
SELECT pg_temp.check_fail('Cross tenant building creator', $q$INSERT INTO buildings(organization_id,name,created_by) VALUES(pg_temp.tid(2),'Invalid',pg_temp.tid(1))$q$,'OrganizationUser');
SELECT pg_temp.check_fail('Cross tenant floor binding', $q$INSERT INTO building_floors(building_id,organization_id,floor_number) VALUES(pg_temp.tid(1),pg_temp.tid(2),4)$q$,'foreign key');
SELECT pg_temp.check_fail('Trainee cannot belong to tenant', $q$INSERT INTO users(organization_id,email,password_hash,role) VALUES(pg_temp.tid(1),'bad@example.test','fixture','Trainee')$q$,'check constraint');
SELECT pg_temp.check_fail('Source immutable after processing', $q$UPDATE source_documents SET storage_url='other' WHERE id=pg_temp.tid(1)$q$,'Draft');
SELECT pg_temp.check_fail('Scenario snapshot immutable', $q$UPDATE scenario_versions SET random_seed=100 WHERE id=pg_temp.tid(1)$q$,'append-only');
SELECT pg_temp.check_fail('Review immutable', $q$DELETE FROM revision_reviews WHERE scenario_version_id=pg_temp.tid(1)$q$,'append-only');
SELECT pg_temp.check_fail('Package update rejected', $q$UPDATE release_packages SET package_url='changed' WHERE release_id=pg_temp.tid(1)$q$,'append-only');
SELECT pg_temp.check_fail('Package delete rejected', $q$DELETE FROM release_packages WHERE release_id=pg_temp.tid(1)$q$,'append-only');
SELECT pg_temp.check_fail('QA immutable', $q$UPDATE validation_runs SET report='{}' WHERE id=pg_temp.tid(1)$q$,'append-only');
SELECT pg_temp.check_fail('Floor snapshot immutable', $q$UPDATE revision_floors SET elevation_meters=9 WHERE id=pg_temp.tid(2)$q$,'append-only');
UPDATE building_floors SET elevation_meters=9 WHERE id=pg_temp.tid(2);
SELECT pg_temp.check_ok('Old floor snapshot survives metadata edit',(SELECT elevation_meters=3 FROM revision_floors WHERE id=pg_temp.tid(2)));
SELECT pg_temp.check_fail('Release cannot close with active QR', $q$UPDATE releases SET status='Superseded' WHERE id=pg_temp.tid(1)$q$,'Deactivate');
SELECT pg_temp.check_fail('Training cannot close with active QR', $q$UPDATE trainings SET status='Closed' WHERE id=pg_temp.tid(1)$q$,'Deactivate');
SELECT pg_temp.check_fail('Published QR cannot be repinned', $q$UPDATE release_qr_codes SET training_id=pg_temp.tid(2),release_id=pg_temp.tid(2) WHERE id=pg_temp.tid(1)$q$,'immutable');
SELECT pg_temp.check_fail('Training policy frozen', $q$UPDATE trainings SET max_attempts=1 WHERE id=pg_temp.tid(1)$q$,'policy frozen');
SELECT pg_temp.check_fail('Wrong organization cannot confirm',$q$SELECT confirm_revision_for_training(pg_temp.tid(1),pg_temp.tid(1),pg_temp.tid(2),pg_temp.tid(2),'Invalid')$q$,'OrganizationUser');
SELECT pg_temp.check_fail('Cannot insert release directly Published',$q$INSERT INTO releases(revision_id,scenario_version_id,building_id,organization_id,confirmation_review_id,status,published_by,published_at) SELECT revision_id,scenario_version_id,building_id,organization_id,confirmation_review_id,'Published',pg_temp.tid(1),now() FROM releases WHERE id=pg_temp.tid(1)$q$,'Built release');
SELECT pg_temp.check_fail('Expired QR cannot activate',$q$INSERT INTO release_qr_codes(release_id,training_id,organization_id,created_by,qr_hash,expires_at) VALUES(pg_temp.tid(1),pg_temp.tid(1),pg_temp.tid(1),pg_temp.tid(1),repeat('9',64),now()-interval '1 hour')$q$,'future expiry');
SELECT pg_temp.check_fail('Device registration cannot change owner',$q$UPDATE user_devices SET user_id=pg_temp.tid(4) WHERE id=pg_temp.tid(1)$q$,'identity immutable');
INSERT INTO revisions(id,building_id,organization_id,uploaded_by,version_label) VALUES(pg_temp.tid(2),pg_temp.tid(1),pg_temp.tid(1),pg_temp.tid(1),'Unuploaded');
SELECT pg_temp.check_fail('Uploaded requires accepted source',$q$UPDATE revisions SET status='Uploaded' WHERE id=pg_temp.tid(2)$q$,'accepted IFC');
UPDATE users SET is_active=false WHERE id=pg_temp.tid(4);
SELECT pg_temp.check_fail('Inactive Trainee cannot start',$q$SELECT start_training_session(pg_temp.tid(4),pg_temp.tid(1),pg_temp.tid(2),'Learn',pg_temp.tid(71),'1','unity-1')$q$,'Active Trainee');
UPDATE users SET is_active=true WHERE id=pg_temp.tid(4);
UPDATE organizations SET is_active=false WHERE id=pg_temp.tid(1);
SELECT pg_temp.check_fail('Inactive organization blocks new session',$q$SELECT start_training_session(pg_temp.tid(3),pg_temp.tid(1),pg_temp.tid(1),'Learn',pg_temp.tid(72),'1','unity-1')$q$,'Active Trainee');
UPDATE organizations SET is_active=true WHERE id=pg_temp.tid(1);
CREATE TEMP TABLE run_sessions(label TEXT PRIMARY KEY,id UUID);
INSERT INTO run_sessions VALUES('main',start_training_session(pg_temp.tid(3),pg_temp.tid(1),pg_temp.tid(1),'Assessment',pg_temp.tid(10),'1','unity-1'));
SELECT pg_temp.check_ok('Trainee with no organization participates',(SELECT organization_id=pg_temp.tid(1) FROM sessions WHERE id=(SELECT id FROM run_sessions WHERE label='main')));
SELECT pg_temp.check_ok('Start retry same key same session',start_training_session(pg_temp.tid(3),pg_temp.tid(1),pg_temp.tid(1),'Assessment',pg_temp.tid(10),'1','unity-1')=(SELECT id FROM run_sessions WHERE label='main'));
SELECT pg_temp.check_fail('Start key conflict',$q$SELECT start_training_session(pg_temp.tid(3),pg_temp.tid(2),pg_temp.tid(1),'Assessment',pg_temp.tid(10),'1','unity-1')$q$,'payload conflict');
SELECT pg_temp.check_fail('Cannot use other trainee device',$q$SELECT start_training_session(pg_temp.tid(3),pg_temp.tid(1),pg_temp.tid(2),'Guided',pg_temp.tid(11),'1','unity-1')$q$,'foreign key');
SELECT pg_temp.check_fail('Cannot skip launch state',$q$UPDATE sessions SET status='Running' WHERE id=(SELECT id FROM run_sessions WHERE label='main')$q$,'Invalid Session');
UPDATE sessions SET status='Launching' WHERE id=(SELECT id FROM run_sessions WHERE label='main');
UPDATE sessions SET status='Running' WHERE id=(SELECT id FROM run_sessions WHERE label='main');
SELECT pg_temp.check_fail('Unknown event schema rejected',$q$SELECT append_session_event(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),1,pg_temp.tid(99),'START','{}',0,'2026-09-11T10:00:00Z','99.0')$q$,'Unsupported event schema');
SELECT pg_temp.check_fail('Cannot complete without result',$q$UPDATE sessions SET status='Completed' WHERE id=(SELECT id FROM run_sessions WHERE label='main')$q$,'Result required');
SELECT pg_temp.check_fail('Wrong event owner',$q$SELECT append_session_event(pg_temp.tid(4),(SELECT id FROM run_sessions WHERE label='main'),1,pg_temp.tid(21),'START','{}',0,'2026-09-11T10:00:00Z')$q$,'owner mismatch');
SELECT pg_temp.check_fail('NULL event owner',$q$SELECT append_session_event(NULL,(SELECT id FROM run_sessions WHERE label='main'),1,pg_temp.tid(21),'START','{}',0,'2026-09-11T10:00:00Z')$q$,'owner mismatch');
SELECT append_session_event(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),2,pg_temp.tid(22),'EXIT','{}',1000,'2026-09-11T10:00:01Z');
SELECT pg_temp.check_fail('Completion rejects missing event gap',$q$SELECT complete_training_session(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),pg_temp.tid(31),2,'{"score":90,"timeTakenSeconds":1,"reachedExit":true,"exitPointId":"exit-1","rubricVersion":"1.0"}','Completed')$q$,'contiguous');
SELECT append_session_event(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),1,pg_temp.tid(21),'START','{}',0,'2026-09-11T10:00:00Z');
SELECT append_session_event(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),1,pg_temp.tid(21),'START','{}',0,'2026-09-11T10:00:00Z');
SELECT pg_temp.check_ok('Duplicate events not counted twice',(SELECT count(*)=2 FROM session_events));
SELECT pg_temp.check_fail('Result cannot commit without terminal Session',$q$DO $$ BEGIN
 INSERT INTO session_results(session_id,completion_key,last_event_sequence,submission_payload,rubric_version,score,time_taken_seconds,reached_exit,exit_point_id)
 SELECT id,pg_temp.tid(80),2,'{}','1.0',90,1,true,'exit-1' FROM run_sessions WHERE label='main';
 SET CONSTRAINTS ALL IMMEDIATE;
 END $$;$q$,'commit together');
SELECT pg_temp.check_fail('Same event identity different payload',$q$SELECT append_session_event(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),1,pg_temp.tid(21),'START','{"different":true}',0,'2026-09-11T10:00:00Z')$q$,'payload conflict');
SELECT pg_temp.check_fail('Negative score rejected',$q$SELECT complete_training_session(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),pg_temp.tid(31),2,'{"score":-1,"timeTakenSeconds":1,"reachedExit":true,"exitPointId":"exit-1","rubricVersion":"1.0"}','Completed')$q$,'check constraint');
SELECT complete_training_session(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),pg_temp.tid(31),2,'{"score":90,"timeTakenSeconds":1,"reachedExit":true,"exitPointId":"exit-1","rubricVersion":"1.0"}','Completed');
SELECT complete_training_session(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),pg_temp.tid(31),2,'{"score":90,"timeTakenSeconds":1,"reachedExit":true,"exitPointId":"exit-1","rubricVersion":"1.0"}','Completed');
SELECT pg_temp.check_ok('Completion retry produces one result',(SELECT count(*)=1 FROM session_results));
SELECT pg_temp.check_fail('Completion retry different payload',$q$SELECT complete_training_session(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),pg_temp.tid(31),2,'{"score":91,"timeTakenSeconds":1,"reachedExit":true,"exitPointId":"exit-1","rubricVersion":"1.0"}','Completed')$q$,'payload conflict');
SELECT pg_temp.check_fail('Terminal Session cannot restart',$q$UPDATE sessions SET status='Running' WHERE id=(SELECT id FROM run_sessions WHERE label='main')$q$,'Terminal session');
SELECT pg_temp.check_fail('New event after completion rejected',$q$SELECT append_session_event(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),3,pg_temp.tid(23),'EXTRA','{}',2000,'2026-09-11T10:00:02Z')$q$,'Running Session');
SELECT append_session_event(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='main'),1,pg_temp.tid(21),'START','{}',0,'2026-09-11T10:00:00Z');
SELECT pg_temp.check_ok('Existing event retry allowed after completion',(SELECT count(*)=2 FROM session_events));
INSERT INTO run_sessions VALUES('historical',start_training_session(pg_temp.tid(3),pg_temp.tid(2),pg_temp.tid(1),'Guided',pg_temp.tid(12),'1','unity-1'));
UPDATE sessions SET status='Launching' WHERE id=(SELECT id FROM run_sessions WHERE label='historical');
UPDATE sessions SET status='Running' WHERE id=(SELECT id FROM run_sessions WHERE label='historical');
UPDATE users SET is_active=false WHERE id=pg_temp.tid(1);
UPDATE release_qr_codes SET is_active=false WHERE id=pg_temp.tid(2);
SELECT pg_temp.check_ok('Deactivate QR after original creator locked',(SELECT NOT is_active FROM release_qr_codes WHERE id=pg_temp.tid(2)));
UPDATE revisions SET status='Superseded' WHERE id=pg_temp.tid(1);
UPDATE releases SET status='Superseded' WHERE id=pg_temp.tid(2);
UPDATE trainings SET status='Closed' WHERE id=pg_temp.tid(2);
UPDATE trainings SET status='Archived' WHERE id=pg_temp.tid(2);
SELECT pg_temp.check_ok('Close/archive Training after parent superseded',(SELECT status='Archived' FROM trainings WHERE id=pg_temp.tid(2)));
SELECT complete_training_session(pg_temp.tid(3),(SELECT id FROM run_sessions WHERE label='historical'),pg_temp.tid(32),0,'{"score":80,"timeTakenSeconds":2,"reachedExit":true,"exitPointId":"exit-1","rubricVersion":"1.0"}','Completed');
SELECT pg_temp.check_ok('Session preserves superseded completion',(SELECT status='CompletedWithSupersededRelease' FROM sessions WHERE id=(SELECT id FROM run_sessions WHERE label='historical')));
UPDATE releases SET status='Revoked',revoked_by=pg_temp.tid(5),revoked_reason='Fixture correction',revoked_at=clock_timestamp() WHERE id=pg_temp.tid(2);
SELECT pg_temp.check_ok('Revoke release after revision superseded',(SELECT status='Revoked' FROM releases WHERE id=pg_temp.tid(2)));
SELECT pg_temp.check_fail('New start with revoked QR rejected',$q$SELECT start_training_session(pg_temp.tid(3),pg_temp.tid(2),pg_temp.tid(1),'Guided',pg_temp.tid(13),'1','unity-1')$q$,'unavailable');
SELECT pg_temp.check_fail('Old QR cannot reactivate',$q$UPDATE release_qr_codes SET is_active=true WHERE id=pg_temp.tid(2)$q$,'rotate');
SELECT pg_temp.check_fail('Audit update rejected',$q$UPDATE audit_logs SET target_entity='changed'$q$,'append-only');
SELECT pg_temp.check_ok('Audit captures confirmation and publish',(SELECT count(*)>=4 FROM audit_logs WHERE action IN ('ConfirmForTraining','Publish')));
SET CONSTRAINTS ALL IMMEDIATE;
SELECT name,outcome FROM test_results ORDER BY name;
SELECT count(*) AS passed_tests FROM test_results;
ROLLBACK;
