<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="*" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="*" />
		<PackageReference Include="MediatR" Version="*" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="*" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Fire3D.Domain\Fire3D.Domain.csproj" />
	</ItemGroup>

</Project>
